### ISSUE TITLE
Incorrect Convert

### ISSUE THREAD

**Issue by mhxw** [kgar/ts-markdown#40]
`t_mapping(t_address,t_uint256)` => `t*mapping(t*address,t_uint256)`

![image](https://github.com/kgar/ts-markdown/assets/32643286/8beab9eb-871e-4244-891a-239b11f31cc1)
<img width="694" alt="image" src="https://github.com/kgar/ts-markdown/assets/32643286/4a14e071-f671-4b4b-8946-b9b2262c785f">

![image](https://github.com/kgar/ts-markdown/assets/32643286/ce7445d9-d8a0-4d7f-a148-5c81cb1182de)

**Comment by kgar** [comment]
Version 1.0.0 should fix this issue.

Thanks for using the library!
